Repository kom-senapati/bot-verse, pull requests merged in 2024-11, with the labels that each got.

#234 Added emoji picker in chat box of bot
  client/package.json
  client/src/pages/Chatbot.tsx
Labels: gssoc-ext, hacktoberfest-accepted, level2, gssoc

#235 Enhance Login Functionality with "Remember Me" Feature
  app/routes.py
  app/templates/login.html
Labels: gssoc-ext, level2, gssoc

#237 feat: Chatbot Version Control
  app/api_routes.py
  app/helpers.py
  app/models.py
  client/bun.lockb
  client/src/components/ChatbotCard.tsx
  client/src/components/modals/update-chatbot-modal.tsx
  client/src/lib/queries.ts
  client/src/pages/Chatbot.tsx
  client/src/pages/ChatbotView.tsx
  client/src/pages/Dashboard.tsx
  client/src/pages/Hub.tsx
  client/src/pages/Profile.tsx
  client/src/types/types.d.ts
Labels: gssoc-ext, level3, gssoc

#240 Added delete button on chatbot card & backend query to remove it from db
  app/api_routes.py
  client/src/components/ChatbotCard.tsx
  client/src/lib/queries.ts
Labels: gssoc-ext, level2, gssoc

#244 feat: Adds Command Panel with shortcuts
  client/bun.lockb
  client/package.json
  client/src/App.tsx
  client/src/components/ProtectedRoute.tsx
  client/src/components/modals/Tts-magic-modal.tsx
  client/src/components/modals/command-modal.tsx
  client/src/components/modals/translate-magic-modal.tsx
  client/src/components/ui/command.tsx
  client/src/components/ui/dialog.tsx
  client/src/pages/Leaderboard.tsx
Labels: gssoc-ext, level3, gssoc

#249 fixes: Chatbot and Images Separation, UI fixes
  app/api_routes.py
  client/bun.lockb
  client/package.json
  client/src/components/ChatbotCard.tsx
  client/src/components/ImageCard.tsx
  client/src/components/ui/tabs.tsx
  client/src/lib/queries.ts
  client/src/pages/Hub.tsx
  client/src/pages/Profile.tsx
Labels: gssoc-ext, level3, gssoc

#252 feat: Image generation modal with enhanced feature
  app/api_routes.py
  client/bun.lockb
  client/src/components/Navbar.tsx
  client/src/components/modals/command-modal.tsx
  client/src/components/modals/imgine-modal.tsx
  client/src/contexts/modals.tsx
  client/src/stores/modal-store.ts
Labels: gssoc-ext, level2, gssoc

#254 feat: image managemnt Page and fixes with deleting and publishing
  app/api_routes.py
  client/src/App.tsx
  client/src/components/ChatbotCard.tsx
  client/src/components/ImageCard.tsx
  client/src/components/Navbar.tsx
  client/src/components/modals/delete-chatbot-modal.tsx
  client/src/contexts/settings-context.tsx
  client/src/lib/queries.ts
  client/src/pages/ChatbotView.tsx
  client/src/pages/Hub.tsx
  client/src/pages/MyImages.tsx
  client/src/pages/Profile.tsx
Labels: gssoc-ext, level2, gssoc

#258 feat: Chatbot management Page with bugs fixed
  client/src/App.tsx
  client/src/components/ChatbotCard.tsx
  client/src/components/Navbar.tsx
  client/src/pages/Hub.tsx
  client/src/pages/MyChatbots.tsx
Labels: gssoc-ext, level3, gssoc

#257 Pass chatbot latest prompt
  app/api_routes.py
Labels: gssoc-ext, level1, gssoc

#259 feat: Analytics information for chatbot and images
  client/src/pages/MyChatbots.tsx
  client/src/pages/MyImages.tsx
Labels: gssoc-ext, level2, gssoc

#260 Added export button to download conversation as csv
  client/package.json
  client/src/pages/Chatbot.tsx
Labels: gssoc-ext, level2, gssoc

#264 feat: i18n Added for 5 langs
  client/bun.lockb
  client/package.json
  client/src/components/ChatbotCard.tsx
  client/src/components/ImageCard.tsx
  client/src/components/LikeAndReport.tsx
  client/src/components/Navbar.tsx
  client/src/components/modals/Tts-magic-modal.tsx
  client/src/components/modals/command-modal.tsx
  client/src/components/modals/create-chatbot-modal.tsx
  client/src/components/modals/delete-chatbot-modal.tsx
  client/src/components/modals/imgine-modal.tsx
  client/src/components/modals/settings-modal.tsx
  client/src/components/modals/share-modal.tsx
  client/src/components/modals/translate-magic-modal.tsx
  client/src/components/modals/update-chatbot-modal.tsx
  client/src/components/modals/update-profile-modal.tsx
  client/src/i18n/i18n.ts
  client/src/i18n/locales/en.ts
  client/src/i18n/locales/es.ts
  client/src/i18n/locales/fr.ts
  client/src/i18n/locales/hi.ts
  client/src/i18n/locales/ja.ts
  client/src/i18n/types.ts
  client/src/main.tsx
  client/src/pages/404.tsx
  client/src/pages/Anonymous.tsx
  client/src/pages/Chatbot.tsx
  client/src/pages/ChatbotView.tsx
  client/src/pages/Dashboard.tsx
  client/src/pages/Hub.tsx
  client/src/pages/Landing.tsx
  client/src/pages/Leaderboard.tsx
  client/src/pages/Login.tsx
  client/src/pages/MyChatbots.tsx
  client/src/pages/MyImages.tsx
  client/src/pages/Profile.tsx
  client/src/pages/Signup.tsx
Labels: gssoc-ext, level3, gssoc

#268 Revamp the leaderborad
  client/src/pages/Leaderboard.tsx
Labels: gssoc-ext, level2, gssoc

#266 Clear all chat with single click on button
  client/src/pages/Chatbot.tsx
Labels: gssoc-ext, level1, gssoc

#271 fixes: UI bugs and translation in some places
  client/src/components/ChatbotCard.tsx
  client/src/components/ui/table.tsx
  client/src/i18n/locales/en.ts
  client/src/pages/Chatbot.tsx
  client/src/pages/Dashboard.tsx
  client/src/pages/Leaderboard.tsx
Labels: gssoc-ext, level2, gssoc

#276 feat: Text-to-handwriting Magic Tool added
  .gitignore
  app/api_routes.py
  app/fonts/handwriting.pkl
  app/fonts/handwriting.ttf
  client/bun.lockb
  client/src/components/modals/command-modal.tsx
  client/src/components/modals/ttH-magic-modal.tsx
  client/src/contexts/modals.tsx
  client/src/index.css
  client/src/pages/Chatbot.tsx
  client/src/stores/modal-store.ts
Labels: gssoc-ext, level3, gssoc

#278 Add Missing Modules
  dev-requirements.txt
  requirements.txt
Labels: gssoc-ext, level1, gssoc

#281 feat: Image Captioning Magic tool
  app/ai.py
  app/api_routes.py
  client/src/components/modals/command-modal.tsx
  client/src/components/modals/image-captioning-magic-modal.tsx
  client/src/contexts/modals.tsx
  client/src/stores/modal-store.ts
  dev-requirements.txt
  requirements.txt
Labels: gssoc-ext, level3, gssoc

#282 feat: QR Code Magic Tool
  client/bun.lockb
  client/package.json
  client/src/components/modals/command-modal.tsx
  client/src/components/modals/qr-magic-modal.tsx
  client/src/contexts/modals.tsx
  client/src/stores/modal-store.ts
Labels: gssoc-ext, level2, gssoc

#284 tweak: Chatbot Chatting page UI revamp
  client/src/pages/Chatbot.tsx
Labels: gssoc-ext, level2, gssoc

#286 feat: Navigation top loader
  client/bun.lockb
  client/package.json
  client/src/App.tsx
  client/src/lib/custom-switch.tsx
Labels: gssoc-ext, level1, gssoc

#288 feat: Page Transition Animation
  client/bun.lockb
  client/package.json
  client/src/App.tsx
  client/src/components/transition.tsx
  client/src/index.css
  client/src/pages/404.tsx
  client/src/pages/Anonymous.tsx
  client/src/pages/Chatbot.tsx
  client/src/pages/ChatbotView.tsx
  client/src/pages/Dashboard.tsx
  client/src/pages/Hub.tsx
  client/src/pages/Imagine.tsx
  client/src/pages/Landing.tsx
  client/src/pages/Leaderboard.tsx
  client/src/pages/Login.tsx
  client/src/pages/MyChatbots.tsx
  client/src/pages/MyImages.tsx
  client/src/pages/Profile.tsx
  client/src/pages/Signup.tsx
  client/src/pages/Test.tsx
Labels: gssoc-ext, level2, gssoc

#291 fixes: Anonymous Chat UI, Navigation bug, UI consistency
  client/src/App.tsx
  client/src/lib/custom-switch.tsx
  client/src/pages/Anonymous.tsx
  client/src/pages/Leaderboard.tsx
Labels: gssoc-ext, level3, gssoc

#293 feat: Terms and Privacy Pages
  client/src/App.tsx
  client/src/components/Footer.tsx
  client/src/components/Navbar.tsx
  client/src/pages/Privacy.tsx
  client/src/pages/Signup.tsx
  client/src/pages/Terms.tsx
Labels: gssoc-ext, level2, gssoc

#294 feat: Adds FAQs Section on Landing Page
  client/bun.lockb
  client/package.json
  client/src/components/ui/accordion.tsx
  client/src/lib/utils.ts
  client/src/pages/Landing.tsx
  client/tailwind.config.js
Labels: gssoc-ext, level2, gssoc

#295 feat: Adds About and Contributors Wall
  client/src/App.tsx
  client/src/lib/custom-switch.tsx
  client/src/pages/About.tsx
Labels: gssoc-ext, level3, gssoc

#298 feat: Adds Greeting PR workflows
  .github/workflows/pr_merge.yml
  .github/workflows/pr_raise.yml
Labels: gssoc-ext, level2, gssoc

#299 feat: Confirm Password and hide button
  .github/pull_request_template.md
  .github/workflows/pr_raise.yml
  client/src/lib/schemas.ts
  client/src/pages/Signup.tsx
Labels: gssoc-ext, level1, gssoc

#300 feat: Adds Read Aloud Switch in chatbot and Settings
  client/bun.lockb
  client/src/components/modals/settings-modal.tsx
  client/src/contexts/settings-context.tsx
  client/src/pages/Chatbot.tsx
Labels: gssoc-ext, level2, gssoc

#301 feat: Social Icons in Footer
  client/src/components/Footer.tsx
Labels: gssoc-ext, level1, gssoc
