Repository kom-senapati/bot-verse, pull requests merged in 2024-10, with the labels that each got.

#9 Fixes #6 #Added CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation, hacktoberfest-accepted

#13 Fixed the error occured while running flask app, Fixed icon position in ChatHub Page & Return Navigation
  routes.py
  templates/chatbot_hub.html
  templates/login.html
  templates/signup.html
Labels: bug, enhancement, hacktoberfest-accepted

#11 fix #10: Authentication error management
  routes.py
  templates/login.html
  templates/signup.html
Labels: bug, hacktoberfest-accepted

#21 fix #20: profile name and username edit
  routes.py
  templates/profile.html
  templates/profile_edit.html
Labels: gssoc-ext, hacktoberfest-accepted

#34 feat: Speech voice change settings
  templates/chatbot.html
  templates/profile.html
Labels: gssoc-ext, hacktoberfest-accepted, gssoc

#41 Transformed update_chatbot.html into a Stunning, Interactive User Experience
  templates/update_chatbot.html
Labels: gssoc-ext, hacktoberfest-accepted, gssoc

#40 Transformed create_chatbot.html into a Stunning, Interactive User Experience
  templates/create_chatbot.html
Labels: gssoc-ext, hacktoberfest-accepted, gssoc

#38 Enhanced Navbar and Add Logout Icon
  templates/chatbot_hub.html
  templates/dashboard.html
  templates/profile.html
Labels: gssoc-ext, hacktoberfest-accepted, gssoc

#44 Feat: Add 6 New Chatbots to the Hub with Enhanced View Functionality
  routes.py
  templates/dashboard.html
Labels: gssoc-ext, hacktoberfest-accepted, gssoc

#46 Add Issues & PR templates
  .github/Issue_templates/BUG_report_issue_template.md
  .github/Issue_templates/Feature_request_issue_template.md
  .github/Pull_Request_template.md
Labels: gssoc-ext, hacktoberfest-accepted, level1, gssoc

#47 feat: Add Github Action to Automatically update contributors Data
  .github/workflows/main.yml
  README.md
Labels: documentation, gssoc-ext, hacktoberfest-accepted, level1, gssoc

#51 Enhanced readme and fixed all .md links to main readme file
  README.md
Labels: documentation, gssoc-ext, hacktoberfest-accepted, level1, gssoc

#49 feat #48: SPA migrations
  models.py
  routes.py
  static/js/app.js
  static/js/chatbot.js
  static/js/chatbot_hub.js
  static/js/create_chatbot.js
  static/js/dashboard.js
  static/js/landing.js
  static/js/login.js
  static/js/logout.js
  static/js/profile.js
  static/js/profile_edit.js
  static/js/signup.js
  templates/base.html
  templates/chatbot.html
  templates/chatbot_hub.html
  templates/create_chatbot.html
  templates/dashboard.html
  templates/index.html
  templates/login.html
  templates/profile.html
  templates/profile_edit.html
  templates/signup.html
  templates/update_chatbot.html
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level3, gssoc

#58 refactor: added type annotations
  ai.py
  app.py
  models.py
  routes.py
  run.py
Labels: gssoc-ext, hacktoberfest-accepted, level2, gssoc

#62 fix #60: fixed Publish and Delete form
  static/js/dashboard.js
  templates/dashboard.html
Labels: gssoc-ext, hacktoberfest-accepted, level1, gssoc

#61 Fixes: #57 Redesign whole website and fix broken ui and theme
  routes.py
  static/app.js
  static/css/tailwind.css
  static/js/landing.js
  tailwind.config.js
  templates/base.html
  templates/chatbot.html
  templates/chatbot_hub.html
  templates/create_chatbot.html
  templates/dashboard.html
  templates/index.html
  templates/login.html
  templates/profile.html
  templates/profile_edit.html
  templates/signup.html
  templates/update_chatbot.html
Labels: gssoc-ext, hacktoberfest-accepted, level3, gssoc

#65 Allowing users to change light mode or dark mode after login
  .gitignore
  static/js/chatbot_hub.js
  static/js/dashboard.js
  static/js/profile.js
  templates/chatbot_hub.html
  templates/dashboard.html
  templates/profile.html
Labels: gssoc-ext, hacktoberfest-accepted, level1, gssoc

#69 feat: more bots
  constants.py
  routes.py
  static/js/dashboard.js
  templates/dashboard.html
Labels: gssoc-ext, hacktoberfest-accepted, level1, gssoc

#72 [perf],[feat] : Changes to routes.py mentioned in issue #66
  routes.py
Labels: gssoc-ext, hacktoberfest-accepted, level2, gssoc

#81 fixes #80: routing and refactor code
  api_routes.py
  app.py
  constants.py
  helpers.py
  routes.py
  templates/chatbot.html
  templates/chatbot_hub.html
  templates/create_chatbot.html
  templates/dashboard.html
  templates/index.html
  templates/login.html
  templates/profile.html
  templates/profile_edit.html
  templates/signup.html
  templates/update_chatbot.html
Labels: gssoc-ext, hacktoberfest-accepted, level3, gssoc

#79 fixes #75: speaker btn
  static/js/chatbot.js
Labels: gssoc-ext, hacktoberfest-accepted, level1, gssoc

#82 fixes #78: Feature a anonymous chat bot
  api_routes.py
  routes.py
  static/app.js
  static/js/anonymous.js
  templates/anonymous.html
  templates/base.html
Labels: gssoc-ext, hacktoberfest-accepted, level3, gssoc

#73 updated: project structure
  app/__init__.py
  app/ai.py
  app/api_routes.py
  app/constants.py
  app/helpers.py
  app/models.py
  app/routes.py
  app/static/app.js
  app/static/css/input.css
  app/static/css/styles.css
  app/static/css/tailwind.css
  app/static/images/hero.jpg
  app/static/js/anonymous.js
  app/static/js/app.js
  app/static/js/chatbot.js
  app/static/js/chatbot_hub.js
  app/static/js/create_chatbot.js
  app/static/js/dashboard.js
  app/static/js/landing.js
  app/static/js/login.js
  app/static/js/logout.js
  app/static/js/profile.js
  app/static/js/profile_edit.js
  app/static/js/signup.js
  app/templates/anonymous.html
  app/templates/base.html
  app/templates/chatbot.html
  app/templates/chatbot_hub.html
  app/templates/create_chatbot.html
  app/templates/dashboard.html
  app/templates/index.html
  app/templates/login.html
  app/templates/profile.html
  app/templates/profile_edit.html
  app/templates/signup.html
  app/templates/update_chatbot.html
  package.json
  tailwind.config.js
Labels: gssoc-ext, hacktoberfest-accepted, level1, gssoc

#85 feat #76: Feature delete all chats
  app/api_routes.py
  app/static/js/chatbot.js
  app/templates/chatbot.html
Labels: gssoc-ext, hacktoberfest-accepted, level1, gssoc

#86 fixes #77: Feature copy and delete actions
  app/api_routes.py
  app/static/js/chatbot.js
  app/templates/chatbot.html
Labels: gssoc-ext, hacktoberfest-accepted, level3, gssoc

#87 fix #84: adds 404 and 500 pages
  app/routes.py
  app/templates/404.html
  app/templates/500.html
Labels: gssoc-ext, hacktoberfest-accepted, level2, gssoc

#95 fix: made the hero text responsive and added the re library
  app/api_routes.py
  app/static/css/tailwind.css
  app/templates/index.html
  tailwind.config.js
Labels: gssoc-ext, hacktoberfest-accepted, level1, gssoc

#100 feat: npm remove use only python
  .gitignore
  README.md
  app/api_routes.py
  app/static/css/tailwind.css
  build_css.py
  package.json
Labels: gssoc-ext, hacktoberfest-accepted, level2, gssoc

#108 Feat(App): Add Eye Icon Functionality for Password Field in Sign-Up/ Sign-In Form
  app/static/js/login.js
  app/static/js/signup.js
  app/templates/login.html
  app/templates/signup.html
Labels: gssoc-ext, hacktoberfest-accepted, level2, gssoc

#109 feat: image generation bot
  app/constants.py
  app/routes.py
  app/static/app.js
  app/static/css/tailwind.css
  app/static/js/imagine.js
  app/templates/dashboard.html
  app/templates/imagine.html
Labels: gssoc-ext, hacktoberfest-accepted, level3, gssoc

#111 Some Tests
  dev-requirements.txt
  pytest.ini
  tests/conftest.py
  tests/test_errors.py
  tests/test_routes.py
  tests/test_run.py
  tests/test_static.py
Labels: gssoc-ext, hacktoberfest-accepted, level3, gssoc

#114 Feat(profile): improve ui of profile section
  app/templates/profile.html
  package-lock.json
Labels: gssoc-ext, hacktoberfest-accepted, level3, gssoc

#119 Added Table metrices in readme
  README.md
Labels: documentation, gssoc-ext, hacktoberfest-accepted, level1, gssoc

#110 Update README.md Contributor Section
  .github/workflows/main.yml
  README.md
Labels: documentation, gssoc-ext, hacktoberfest-accepted, level1, gssoc

#122 FIX Implement GitHub PR Issue Checker Workflow
  .github/workflows/pr-checker.yml
Labels: gssoc-ext, hacktoberfest-accepted, level2, gssoc

#128 feat: save images
  app/api_routes.py
  app/models.py
  app/routes.py
  app/static/js/imagine.js
  app/templates/imagine.html
Labels: gssoc-ext, hacktoberfest-accepted, level3, gssoc

#130 feat: like and report images and bots
  app/api_routes.py
  app/models.py
  app/static/js/chatbot_hub.js
  app/static/js/gallery.js
  app/templates/chatbot_hub.html
  app/templates/gallery.html
Labels: gssoc-ext, hacktoberfest-accepted, level2, gssoc

#136 Add Toggle Dark/Light Mode Button with attractive icons
  Darkmode/dark.css
  Darkmode/dark.html
  Darkmode/dark.js
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level1, gssoc

#137 feat: Implement new dropdown component
  app/static/css/tailwind.css
  app/static/js/landing.js
  app/templates/index.html
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level1, gssoc

#142 feat: settings page with all required settings
  app/routes.py
  app/static/app.js
  app/static/css/tailwind.css
  app/static/js/profile.js
  app/static/js/settings.js
  app/templates/profile.html
  app/templates/settings.html
Labels: gssoc-ext, hacktoberfest-accepted, level3, gssoc

#143 feat: welcome section with things of the day
  app/api_routes.py
  app/static/css/tailwind.css
  app/static/js/dashboard.js
  app/templates/dashboard.html
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level3, gssoc

#151 feat: react setup with routing
  client/.gitignore
  client/README.md
  client/bun.lockb
  client/eslint.config.js
  client/index.html
  client/package.json
  client/postcss.config.js
  client/public/vite.svg
  client/src/App.css
  client/src/App.tsx
  client/src/assets/react.svg
  client/src/index.css
  client/src/main.tsx
  client/src/pages/404.tsx
  client/src/pages/Anonymous.tsx
  client/src/pages/Chatbot.tsx
  client/src/pages/Dashboard.tsx
  client/src/pages/Hub.tsx
  client/src/pages/Imagine.tsx
  client/src/pages/Landing.tsx
  client/src/pages/Login.tsx
  client/src/pages/Profile.tsx
  client/src/pages/Signup.tsx
  client/src/pages/UserProfile.tsx
  client/src/vite-env.d.ts
  client/tailwind.config.js
  client/tsconfig.app.json
  client/tsconfig.json
  client/tsconfig.node.json
  client/vite.config.ts
Labels: gssoc-ext, hacktoberfest-accepted, level3, gssoc

#153 feat: landing and UI components
  client/bun.lockb
  client/package.json
  client/src/components/Button.tsx
  client/src/components/Input.tsx
  client/src/components/Navbar.tsx
  client/src/components/Separator.tsx
  client/src/index.css
  client/src/lib/schemas.ts
  client/src/lib/utils.ts
  client/src/pages/404.tsx
  client/src/pages/Dashboard.tsx
  client/src/pages/Landing.tsx
  package-lock.json
Labels: gssoc-ext, hacktoberfest-accepted, level2, gssoc

#157 Feat(.github): Updated Github Action for Issue and Bug Reporting Templates
  .github/ISSUE_TEMPLATE/BUG_report_issue_template.md
  .github/ISSUE_TEMPLATE/BUG_report_issue_template.yml
  .github/ISSUE_TEMPLATE/ENHANCEMENT_issue_template.md
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: gssoc-ext, hacktoberfest-accepted, level1, gssoc

#164 Migration: Dashboard and create/delete chatbot
  app/api_routes.py
  app/models.py
  client/bun.lockb
  client/package.json
  client/src/App.tsx
  client/src/components/Footer.tsx
  client/src/components/modals/create-chatbot-modal.tsx
  client/src/components/modals/delete-chatbot-modal.tsx
  client/src/components/ui/textarea.tsx
  client/src/contexts/modals.tsx
  client/src/lib/queries.ts
  client/src/lib/schemas.ts
  client/src/lib/utils.ts
  client/src/pages/Dashboard.tsx
  client/src/pages/Login.tsx
  client/src/stores/modal-store.ts
  client/src/types/default-modal-store.ts
  client/src/types/types.d.ts
Labels: gssoc-ext, hacktoberfest-accepted, level3, gssoc

#167 migration: chatting and hub with some features
  app/api_routes.py
  app/models.py
  client/bun.lockb
  client/package.json
  client/src/App.tsx
  client/src/components/Navbar.tsx
  client/src/components/Separator.tsx
  client/src/components/modals/update-chatbot-modal.tsx
  client/src/contexts/modals.tsx
  client/src/lib/queries.ts
  client/src/lib/schemas.ts
  client/src/lib/utils.ts
  client/src/pages/Chatbot.tsx
  client/src/pages/Dashboard.tsx
  client/src/pages/Hub.tsx
  client/src/pages/Landing.tsx
Labels: gssoc-ext, hacktoberfest-accepted, level3, gssoc

#170 migration: imagine and anonymous pages with other features
  app/api_routes.py
  client/src/App.tsx
  client/src/components/Navbar.tsx
  client/src/lib/queries.ts
  client/src/pages/Anonymous.tsx
  client/src/pages/Dashboard.tsx
  client/src/pages/Imagine.tsx
  client/src/pages/Profile.tsx
  client/src/pages/UserProfile.tsx
Labels: gssoc-ext, hacktoberfest-accepted, level3, gssoc

#175 feat: A copilot assistant
  client/bun.lockb
  client/package.json
  client/src/App.tsx
  client/src/components/ProtectedRoute.tsx
  client/src/components/modals/create-chatbot-modal.tsx
  client/src/lib/utils.ts
  client/src/pages/Dashboard.tsx
Labels: gssoc-ext, hacktoberfest-accepted, level2, gssoc

#177 Fixes migration code
  app/api_routes.py
  client/bun.lockb
  client/package.json
  client/src/App.tsx
  client/src/components/ChatbotCard.tsx
  client/src/components/ImageCard.tsx
  client/src/components/LikeAndReport.tsx
  client/src/components/Navbar.tsx
  client/src/components/modals/settings-modal.tsx
  client/src/components/ui/select.tsx
  client/src/components/ui/switch.tsx
  client/src/contexts/modals.tsx
  client/src/contexts/settings-context.tsx
  client/src/index.css
  client/src/lib/queries.ts
  client/src/pages/Dashboard.tsx
  client/src/pages/Hub.tsx
  client/src/pages/Profile.tsx
  client/src/stores/modal-store.ts
  client/tailwind.config.js
Labels: gssoc-ext, hacktoberfest-accepted, level3, gssoc

#180 fix: Profile like report API fixes, contribution score
  app/api_routes.py
  app/helpers.py
  app/models.py
  app/routes.py
  client/bun.lockb
  client/package.json
  client/src/App.tsx
  client/src/components/LikeAndReport.tsx
  client/src/components/ProtectedRoute.tsx
  client/src/components/ui/badge.tsx
  client/src/lib/queries.ts
  client/src/pages/Dashboard.tsx
  client/src/pages/Hub.tsx
  client/src/pages/Landing.tsx
  client/src/pages/Profile.tsx
  client/src/types/types.d.ts
Labels: gssoc-ext, hacktoberfest-accepted, level3, gssoc

#182 feat: BUTTON TO GO TOP
  client/bun.lockb
  client/package.json
  client/src/App.tsx
Labels: gssoc-ext, hacktoberfest-accepted, level1, gssoc

#183 feat: Loading Skeletons
  client/src/components/modals/update-profile-modal.tsx
  client/src/components/ui/skeleton.tsx
  client/src/pages/Chatbot.tsx
  client/src/pages/Dashboard.tsx
  client/src/pages/Hub.tsx
  client/src/pages/Imagine.tsx
  client/src/pages/Profile.tsx
Labels: gssoc-ext, hacktoberfest-accepted, level2, gssoc

#186 feat: Multiple themes
  client/src/App.tsx
  client/src/components/ChatbotCard.tsx
  client/src/components/LikeAndReport.tsx
  client/src/components/modals/settings-modal.tsx
  client/src/components/theme-toggle.tsx
  client/src/contexts/settings-context.tsx
  client/src/index.css
  client/src/pages/Chatbot.tsx
  client/src/pages/Dashboard.tsx
  client/tailwind.config.js
Labels: gssoc-ext, hacktoberfest-accepted, level2, gssoc

#187 fixes: API and bugs in data fetching
  app/api_routes.py
  client/src/components/BotsLoading.tsx
  client/src/components/ChatbotCard.tsx
  client/src/components/Navbar.tsx
  client/src/lib/queries.ts
  client/src/lib/utils.ts
  client/src/pages/Dashboard.tsx
  client/src/pages/Hub.tsx
  client/src/pages/Profile.tsx
Labels: gssoc-ext, hacktoberfest-accepted, level2, gssoc

#192 Add workflows for Github
  .github/workflows/auto_lable_issue.yml
  .github/workflows/issue-workflow.yml
  .github/workflows/pr-workflow.yml
  .github/workflows/up_for_graps.yml
Labels: gssoc-ext, hacktoberfest-accepted, level2, gssoc

#197 feat: User specific API key adding option
  app/ai.py
  app/api_routes.py
  client/src/components/modals/settings-modal.tsx
  client/src/contexts/settings-context.tsx
  client/src/pages/Anonymous.tsx
  client/src/pages/Chatbot.tsx
Labels: gssoc-ext, hacktoberfest-accepted, level2, gssoc

#198 feat: Leaderboard on basis of contribution score
  app/api_routes.py
  app/data_fetcher.py
  app/models.py
  client/src/App.tsx
  client/src/components/Navbar.tsx
  client/src/lib/queries.ts
  client/src/pages/Dashboard.tsx
  client/src/pages/Leaderboard.tsx
  client/src/types/types.d.ts
Labels: gssoc-ext, hacktoberfest-accepted, level2, gssoc

#199 feat: development docs
  DEVELOPMENT.md
  README.md
Labels: documentation, gssoc-ext, hacktoberfest-accepted, level2, gssoc

#200 feat: Multiple AI engines
  app/ai.py
  app/api_routes.py
  client/src/components/modals/settings-modal.tsx
  client/src/components/ui/input.tsx
  client/src/contexts/settings-context.tsx
  client/src/pages/Anonymous.tsx
  client/src/pages/Chatbot.tsx
  client/src/types/types.d.ts
  dev-requirements.txt
  requirements.txt
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level3, gssoc

#204 feat: chatbot view and share option
  app/api_routes.py
  client/bun.lockb
  client/package.json
  client/src/App.tsx
  client/src/components/ChatbotCard.tsx
  client/src/components/modals/share-modal.tsx
  client/src/components/ui/avatar.tsx
  client/src/contexts/modals.tsx
  client/src/lib/queries.ts
  client/src/pages/ChatbotView.tsx
  client/src/pages/Hub.tsx
  client/src/stores/modal-store.ts
  client/tailwind.config.js
Labels: gssoc-ext, hacktoberfest-accepted, level3, gssoc

#205 feat: Option to Comment on chatbot
  app/api_routes.py
  app/models.py
  client/src/lib/queries.ts
  client/src/pages/ChatbotView.tsx
  client/src/types/types.d.ts
Labels: gssoc-ext, hacktoberfest-accepted, level3, gssoc

#208 fixes: UI bugs, Actions and Hubs Card improved
  app/api_routes.py
  app/models.py
  client/bun.lockb
  client/package.json
  client/src/components/ChatbotCard.tsx
  client/src/components/ImageCard.tsx
  client/src/components/LikeAndReport.tsx
  client/src/components/ui/dropdown-menu.tsx
  client/src/lib/queries.ts
  client/src/pages/Chatbot.tsx
  client/src/pages/ChatbotView.tsx
  client/src/pages/Hub.tsx
  client/src/pages/Profile.tsx
  client/src/types/types.d.ts
Labels: gssoc-ext, hacktoberfest-accepted, level3, gssoc

#206 Enhanced Error Handling for API Calls and API Key Validation #201
  app/ai.py
  app/constants.py
  app/data_fetcher.py
  app/helpers.py
Labels: gssoc-ext, hacktoberfest-accepted, level2, gssoc

#210 fixes: authentication headers and 422 error
  client/src/components/modals/create-chatbot-modal.tsx
  client/src/components/modals/delete-chatbot-modal.tsx
  client/src/components/modals/update-chatbot-modal.tsx
  client/src/components/modals/update-profile-modal.tsx
  client/src/lib/queries.ts
  client/src/pages/Anonymous.tsx
  client/src/pages/Chatbot.tsx
  client/src/pages/ChatbotView.tsx
  client/src/pages/Imagine.tsx
Labels: gssoc-ext, hacktoberfest-accepted, level2, gssoc

#214 fixes: AI engine section and chats auto scroll
  .gitignore
  client/bun.lockb
  client/src/contexts/settings-context.tsx
  client/src/pages/Chatbot.tsx
  client/src/pages/Imagine.tsx
Labels: gssoc-ext, hacktoberfest-accepted, level2, gssoc

#216 feat: settings option on chatbot page
  client/src/pages/Chatbot.tsx
Labels: gssoc-ext, hacktoberfest-accepted, level2, gssoc

#211 Added speech recognition and speech synthesis methods with mic option in chatbot page
  client/src/hooks/useSpeech.tsx
  client/src/pages/Chatbot.tsx
Labels: gssoc-ext, hacktoberfest-accepted, level2, gssoc

#228 Added api key and engine setting in local storage
  client/src/components/modals/settings-modal.tsx
  client/src/contexts/settings-context.tsx
Labels: gssoc-ext, hacktoberfest-accepted, level1, gssoc

#231 feat: Pre build templates to create chatbot
  client/bun.lockb
  client/package.json
  client/src/components/modals/create-chatbot-modal.tsx
  client/src/components/ui/scroll-area.tsx
  client/src/lib/utils.ts
  client/src/pages/Dashboard.tsx
Labels: gssoc-ext, hacktoberfest-accepted, level2, gssoc

#232 feat: Categories and Filter with search bar
  app/api_routes.py
  app/models.py
  client/bun.lockb
  client/src/components/modals/create-chatbot-modal.tsx
  client/src/components/modals/translate-magic-modal.tsx
  client/src/components/modals/update-chatbot-modal.tsx
  client/src/lib/schemas.ts
  client/src/lib/utils.ts
  client/src/pages/ChatbotView.tsx
  client/src/pages/Hub.tsx
  client/src/types/types.d.ts
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level3, gssoc
